package com.craftfire.authapi.enums;

public enum CacheGroup {
    BAN, BAN_COUNT, BAN_LIST, POST, POST_COUNT, POST_COUNT_TOTAL, POST_LAST, POST_LAST_USER, POST_LIST, PM, PM_SENT,
    PM_RECEIVED, PM_SENT_COUNT, PM_RECEIVED_COUNT, THREAD, THREAD_COUNT, THREAD_COUNT_TOTAL, THREAD_LAST,
    THREAD_LAST_USER, THREAD_POSTS, THREAD_LIST, USER, USER_GROUP, USER_LAST_REG, USER_COUNT, USER_USERNAME, USER_ID,
    USER_IP, GROUP, GROUP_COUNT, GROUP_LIST, GROUP_ID, URL_HOME, URL_FORUM, IS_BANNED, IS_REGISTERED
}
